version: "3.9"

services:
  
  server:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
      - "3000:3000"
    # depends_on: 
    #   - db
    networks:
      - server_backend
    
networks:
  server_backend:
    driver: "bridge"
    external: false
    name: server_backend