version: "3.9"

services:
  
  server:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"
      - "3001:3001"
    # depends_on: 
    #   - db
    networks:
      - server_backend
    
networks:
  server_backend:
    driver: "bridge"
    external: false
    name: server_backend