// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: data.proto

package datapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reporte struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Carnet int32  `protobuf:"varint,1,opt,name=Carnet,proto3" json:"Carnet,omitempty"`
	Nombre string `protobuf:"bytes,2,opt,name=Nombre,proto3" json:"Nombre,omitempty"`
	Curso  string `protobuf:"bytes,3,opt,name=Curso,proto3" json:"Curso,omitempty"`
	Fecha  string `protobuf:"bytes,4,opt,name=Fecha,proto3" json:"Fecha,omitempty"`
	Cuerpo string `protobuf:"bytes,5,opt,name=Cuerpo,proto3" json:"Cuerpo,omitempty"`
}

func (x *Reporte) Reset() {
	*x = Reporte{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reporte) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reporte) ProtoMessage() {}

func (x *Reporte) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reporte.ProtoReflect.Descriptor instead.
func (*Reporte) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

func (x *Reporte) GetCarnet() int32 {
	if x != nil {
		return x.Carnet
	}
	return 0
}

func (x *Reporte) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Reporte) GetCurso() string {
	if x != nil {
		return x.Curso
	}
	return ""
}

func (x *Reporte) GetFecha() string {
	if x != nil {
		return x.Fecha
	}
	return ""
}

func (x *Reporte) GetCuerpo() string {
	if x != nil {
		return x.Cuerpo
	}
	return ""
}

type Asistencia struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Carnet       int32  `protobuf:"varint,1,opt,name=Carnet,proto3" json:"Carnet,omitempty"`
	Nombre       string `protobuf:"bytes,2,opt,name=Nombre,proto3" json:"Nombre,omitempty"`
	NombreEvento string `protobuf:"bytes,3,opt,name=NombreEvento,proto3" json:"NombreEvento,omitempty"`
	IdEvento     int32  `protobuf:"varint,4,opt,name=IdEvento,proto3" json:"IdEvento,omitempty"`
	Imagen       string `protobuf:"bytes,5,opt,name=Imagen,proto3" json:"Imagen,omitempty"`
	Fecha        string `protobuf:"bytes,6,opt,name=Fecha,proto3" json:"Fecha,omitempty"`
}

func (x *Asistencia) Reset() {
	*x = Asistencia{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asistencia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asistencia) ProtoMessage() {}

func (x *Asistencia) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asistencia.ProtoReflect.Descriptor instead.
func (*Asistencia) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{1}
}

func (x *Asistencia) GetCarnet() int32 {
	if x != nil {
		return x.Carnet
	}
	return 0
}

func (x *Asistencia) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Asistencia) GetNombreEvento() string {
	if x != nil {
		return x.NombreEvento
	}
	return ""
}

func (x *Asistencia) GetIdEvento() int32 {
	if x != nil {
		return x.IdEvento
	}
	return 0
}

func (x *Asistencia) GetImagen() string {
	if x != nil {
		return x.Imagen
	}
	return ""
}

func (x *Asistencia) GetFecha() string {
	if x != nil {
		return x.Fecha
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_data_proto protoreflect.FileDescriptor

var file_data_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x7d, 0x0a, 0x07, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x43, 0x61, 0x72, 0x6e, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x43,
	0x61, 0x72, 0x6e, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x75,
	0x72, 0x73, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x65, 0x63, 0x68, 0x61, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x46, 0x65, 0x63, 0x68, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x75, 0x65,
	0x72, 0x70, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x75, 0x65, 0x72, 0x70,
	0x6f, 0x22, 0xaa, 0x01, 0x0a, 0x0a, 0x41, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x69, 0x61,
	0x12, 0x16, 0x0a, 0x06, 0x43, 0x61, 0x72, 0x6e, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x43, 0x61, 0x72, 0x6e, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x6d, 0x62,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x49, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x65, 0x63, 0x68,
	0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x46, 0x65, 0x63, 0x68, 0x61, 0x22, 0x2c,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x73, 0x0a, 0x0b,
	0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x53,
	0x61, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x1a, 0x0e, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0e, 0x53,
	0x61, 0x76, 0x65, 0x41, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x12, 0x10, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x1a,
	0x0e, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_proto_rawDescOnce sync.Once
	file_data_proto_rawDescData = file_data_proto_rawDesc
)

func file_data_proto_rawDescGZIP() []byte {
	file_data_proto_rawDescOnce.Do(func() {
		file_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_proto_rawDescData)
	})
	return file_data_proto_rawDescData
}

var file_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_data_proto_goTypes = []interface{}{
	(*Reporte)(nil),    // 0: data.Reporte
	(*Asistencia)(nil), // 1: data.Asistencia
	(*Response)(nil),   // 2: data.Response
}
var file_data_proto_depIdxs = []int32{
	0, // 0: data.DataService.SaveReporte:input_type -> data.Reporte
	1, // 1: data.DataService.SaveAsistencia:input_type -> data.Asistencia
	2, // 2: data.DataService.SaveReporte:output_type -> data.Response
	2, // 3: data.DataService.SaveAsistencia:output_type -> data.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_proto_init() }
func file_data_proto_init() {
	if File_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reporte); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Asistencia); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_proto_goTypes,
		DependencyIndexes: file_data_proto_depIdxs,
		MessageInfos:      file_data_proto_msgTypes,
	}.Build()
	File_data_proto = out.File
	file_data_proto_rawDesc = nil
	file_data_proto_goTypes = nil
	file_data_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataServiceClient interface {
	SaveReporte(ctx context.Context, in *Reporte, opts ...grpc.CallOption) (*Response, error)
	SaveAsistencia(ctx context.Context, in *Asistencia, opts ...grpc.CallOption) (*Response, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) SaveReporte(ctx context.Context, in *Reporte, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/data.DataService/SaveReporte", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) SaveAsistencia(ctx context.Context, in *Asistencia, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/data.DataService/SaveAsistencia", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
type DataServiceServer interface {
	SaveReporte(context.Context, *Reporte) (*Response, error)
	SaveAsistencia(context.Context, *Asistencia) (*Response, error)
}

// UnimplementedDataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataServiceServer struct {
}

func (*UnimplementedDataServiceServer) SaveReporte(context.Context, *Reporte) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveReporte not implemented")
}
func (*UnimplementedDataServiceServer) SaveAsistencia(context.Context, *Asistencia) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveAsistencia not implemented")
}

func RegisterDataServiceServer(s *grpc.Server, srv DataServiceServer) {
	s.RegisterService(&_DataService_serviceDesc, srv)
}

func _DataService_SaveReporte_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reporte)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).SaveReporte(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.DataService/SaveReporte",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).SaveReporte(ctx, req.(*Reporte))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_SaveAsistencia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Asistencia)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).SaveAsistencia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.DataService/SaveAsistencia",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).SaveAsistencia(ctx, req.(*Asistencia))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "data.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveReporte",
			Handler:    _DataService_SaveReporte_Handler,
		},
		{
			MethodName: "SaveAsistencia",
			Handler:    _DataService_SaveAsistencia_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data.proto",
}
