version: "3.9"

services:
  client:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "6001:6001"
    networks:
      - server_backend

networks:
  server_backend:
    driver: "bridge"
    external: false
    name: server_backend